# Generated by Django 3.2.1 on 2021-05-13 05:17

import autoslug.fields
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='x',
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='x'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(default=django.contrib.auth.models.User, primary_key=True, serialize=False),
        ),
    ]
