# Generated by Django 3.2.1 on 2021-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dilemmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('text', models.TextField()),
                ('response_0', models.CharField(blank=True, default='', max_length=64)),
                ('response_1', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
