# Generated by Django 3.2.1 on 2021-05-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilemmas',
            name='id',
            field=models.BigAutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dilemmas',
            name='response_0',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dilemmas',
            name='response_1',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dilemmas',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
