# Generated by Django 3.2.1 on 2021-05-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilemmas',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
