# Generated by Django 3.2.1 on 2021-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics_app', '0002_alter_dilemmas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilemmas',
            name='image',
            field=models.ImageField(upload_to='ethics_app/image_assets'),
        ),
    ]
