# Generated by Django 3.2.1 on 2021-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics_app', '0004_profiledata_userreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='user_header_image',
            field=models.ImageField(blank=True, upload_to='ethics_app/image_assets'),
        ),
        migrations.AlterField(
            model_name='dilemmas',
            name='image',
            field=models.ImageField(blank=True, upload_to='ethics_app/image_assets'),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='user_header',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='user_thumbnail',
            field=models.ImageField(blank=True, upload_to='ethics_app/image_assets'),
        ),
    ]
