# Generated by Django 3.2.1 on 2021-05-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics_app', '0005_auto_20210506_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='ethics_app/image_assets')),
                ('header', models.CharField(max_length=64)),
                ('header_image', models.ImageField(blank=True, upload_to='ethics_app/image_assets')),
                ('bio', models.TextField()),
                ('gender', models.CharField(max_length=32)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileData',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='birth_date',
        ),
    ]
