# Generated by Django 3.2.1 on 2021-05-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethics_app', '0006_auto_20210508_0155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReg',
        ),
    ]
