# Generated by Django 3.2.1 on 2021-05-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethics_app', '0008_auto_20210511_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dilemmas',
            old_name='optionA',
            new_name='response_0',
        ),
        migrations.RenameField(
            model_name='dilemmas',
            old_name='optionB',
            new_name='response_1',
        ),
        migrations.RenameField(
            model_name='dilemmas',
            old_name='dilemma',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='profileinfo',
            old_name='header_image',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='profileinfo',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
